version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    environment:
      - LOCALSTACK=true
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,dynamodb,lambda,cloudwatch
      - DEBUG=1 